export const SEARCHING_ACTION: string = 'SEARCHING_ACTION';
export const SEARCH_RESULT_ACTION: string = 'SEARCH_RESULT_ACTION';
export const TAG_SEARCH_RESULT_ACTION: string = 'TAG_SEARCH_RESULT_ACTION';
export const SEARCH_OPTION_CHANGE_ACTION: string = 'SEARCH_OPTION_CHANGE_ACTION';

